/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:18a3899b-d3c9-4263-95a4-880d8b8ef0eb",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_fURw9aPth",
    "aws_user_pools_web_client_id": "383cd4gtrub1n6s3k2q62ciuhv",
    "oauth": {}
};


export default awsmobile;
